### PR TITLE
Port AxVMArchPerCpu trait into this crate

### PR DESCRIPTION
**Pull request by hky1999**

### CODE REVIEW

**Comment by aarkegz** [comment]
Please move `PerCpu` here too.

**Comment by hky1999** [comment]
> Please move `PerCpu` here too.

Done, and rename them to `AxArchPerCpu` and `AxPerCpu`.

**Comment by hky1999** [comment]
Rust Doc of `AxPerCpu` in `src/percpu.rs` failed to pass [doctest](https://github.com/arceos-hypervisor/axvcpu/actions/runs/10493076109/job/29066131862?pr=10) @aarkegz 

I have to use "```ignore" to bypass it, see this [commit](https://github.com/arceos-hypervisor/axvcpu/pull/10/commits/2c08c99fc055bd3b52fa0cd8a5d56822a3db34f9)

**Comment by aarkegz** [comment]
> Rust Doc of `AxPerCpu` in `src/percpu.rs` failed to pass [doctest](https://github.com/arceos-hypervisor/axvcpu/actions/runs/10493076109/job/29066131862?pr=10) @aarkegz
> 
> I have to use "```ignore" to bypass it, see this [commit](https://github.com/arceos-hypervisor/axvcpu/pull/10/commits/2c08c99fc055bd3b52fa0cd8a5d56822a3db34f9)

I'll check it latter tonight.

**Comment by hky1999** [comment]
> > Rust Doc of `AxPerCpu` in `src/percpu.rs` failed to pass [doctest](https://github.com/arceos-hypervisor/axvcpu/actions/runs/10493076109/job/29066131862?pr=10) @aarkegz
> > I have to use "```ignore" to bypass it, see this [commit](https://github.com/arceos-hypervisor/axvcpu/pull/10/commits/2c08c99fc055bd3b52fa0cd8a5d56822a3db34f9)
> 
> I'll check it latter tonight.

Remember to check this PR tonight

**Review by aarkegz — APPROVED** [review]

**Pull request merged**
